version: '3.3'
services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7

    restart: always
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: peng
       MYSQL_USER: peng
       MYSQL_PASSWORD: admin

  postgres:
    image: postgres

    restart: always
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: peng
       POSTGRES_PASSWORD: admin
